### ISSUE TITLE
permission denied for `android-svc download`

### ISSUE THREAD

**Issue by mortee** [T-vK/android-svc#2]
Installed Termux and android-svc_0.1.0_all.deb on a LineageOS 17 rooted phone, but when I try to run android-svc download, it says "Permission denied".

```
~ $ android-svc download
Permission denied
Failed to retrieve Android version in GetAndroidVersion

~ $ sudo android-svc download
Permission denied
~ $
```

**Comment by T-vK** [comment]
Huh, interesting. Can you tell me that you get when running this?

``` Bash
source "${PREFIX}/lib/android-svc-lib.sh"
GetAndroidVersion
```

If that returns an error or nothing, the output of `getprop` would also be interesting.
I'm currently relying on the property `ro.build.version.release` to exist, if this is not the case on LineageOS 17, I have to find an alternative property to check. Ideally one that exists on all Android devices. If you share your `getprop` output, you might wanna check it for personal information and remove it before posting.


One more thing: Is LineageOS 17 based on an Android version newer than Android 10? I'm asking because in a recent issue it turned out that I need to fix android-svc to work with Andorid 11: https://github.com/T-vK/android-svc/issues/1#issuecomment-797147149

**Comment by T-vK** [comment]
You might wanna try the new release. https://github.com/T-vK/android-svc/releases/tag/0.2.1

**Comment by T-vK** [comment]
I tested it on LineageOS 17 now and it works fine for me.

**Comment by mortee** [comment]
I'm sorry for failing to reply to the questions back then. Apparently, the notifications about these comments totally went over my head.

**Comment by T-vK** [comment]
No worries. If your problem still exists, we can reopen the issue.
